Added header and section to check if the script is being sourced

diff --git a/bin/psenv b/bin/psenv
--- a/bin/psenv
+++ b/bin/psenv
@@ -1,14 +1,25 @@
 #!/usr/bin/env bash
-# ps-dotfiles script for sourcing environment variables
+#Title         :psenv
+#Description   :Utility script for setting PeopleSoft-specific environment
+#               variables under Unix/Linux
+#Author        :JR Bing
+#==============================================================================
 
 PS_ENV_HOME=$HOME/environments
 PSENV_LIBDIR=$SPHOME/lib
 . $PSENV_LIBDIR/libpsenv.sh
 
+########################
 # Check for environments
+########################
+
 check_for_environment_dir
 
+
+########################################
 # Parse any options passed to the script
+########################################
+
 while :
 do
   case $1 in
@@ -33,7 +44,7 @@ do
       break
       ;;
     -*)
-      printf "WARN: Unknown option (ignored): $1 \n" >&2
+      printf "[WARNING]: Unknown option (ignored): $1 \n" >&2
       shift
       ;;
     *)
@@ -42,18 +53,26 @@ do
   esac
 done
 
-ENVIRONMENT=$1                           # Pass in the environment
+#################################################
+# Source environment variables from configuration
+# if the script is being sourced
+#################################################
 
-if [ $(contains_environment "${ENV_FILES[@]}" $ENVIRONMENT) == "y" ]; then
-    printf "Environment file for $1 found\n"
-    environment_reset                        # Reset the impacted environment variables
-    restore_library_path                     # Change the library path to it's previous setting
-    restore_path                             # Change the path to it's previous setting
-    source_env_file $ENVIRONMENT             # Source the environment file
-    source_psconfig                          # Run the psconfig.sh script
-    set_library_path                         # Set the LD_LIBRARY_PATH
-    set_path                                 # Set the PATH
-  else
-    printf "Environment file for $1 not found\n"
+ENVIRONMENT=$1  # Pass in the environment
+
+if [[ "$BASH_SOURCE" == "$0" ]]; then
+    exit 0
+  elif [[ "$BASH_SOURCE" != "$0" ]]; then
+    if [ $(contains_environment "${ENV_FILES[@]}" $ENVIRONMENT) == "y" ]; then
+        printf "Environment file for $1 found\n"
+        environment_reset                        # Reset the impacted environment variables
+        restore_library_path                     # Change the library path to it's previous setting
+        restore_path                             # Change the path to it's previous setting
+        source_env_file $ENVIRONMENT             # Source the environment file
+        source_psconfig                          # Run the psconfig.sh script
+        set_library_path                         # Set the LD_LIBRARY_PATH
+        set_path                                 # Set the PATH
+      else
+        printf "Environment file for $1 not found\n"
+    fi
 fi
-
